name: Create new release version, build and push

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get next version
        uses: thenativeweb/get-next-version@2.0.0
        id: get_next_version
      - name: Create new release
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION
      - name: Build Docker Image
        run: |
          echo "Building image with tag: $NEXT_VERSION"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/room-service:$NEXT_VERSION .
      - name: Tag with latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/room-service:${NEXT_VERSION} ${{ secrets.DOCKER_USERNAME }}/room-service:latest
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:$NEXT_VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
